repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.280'
    hooks:
      - id: ruff
        args: ["--config", "pyproject.toml", "--fix", "--fix-only", "--show-fixes"]

  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
