[tool.black]
line-length = 120
target-version = ["py311"]
exclude = '''
(
    \.eggs
  | \.git
  | \.tox
  | build
  | dist
  | venv
  | docs
)
'''

[tool.isort]
profile = "black"
line_length = 120
include_trailing_comma = true
combine_as_imports = true
remove_redundant_aliases = true

[tool.ruff]
select = ["E", "F", "I", "SIM", "ARG", "T20", "Q", "N", "ANN", "RET", "PT", "C4", "C90"]
ignore = ["ANN101", "ANN002", "ANN003", "I001", "F401"]
extend-exclude = ["pyproject.toml"]
unfixable = ["T20", "E711"]
